### PR TITLE
New pro forma and developer models

### PR DESCRIPTION
**Pull request by pksohn**
Hi all,

This PR implements the SEMCOG pro forma and residential developer models using the new `developer` package. Please see the proforma.md file for a writeup of changes. This provides a direct translation of the baseline functionality, and does not implement new features like pipeline, extra callback functions, etc - with the exception of adding construction financing, which is built into the core SqFtProForma class.

Hopefully this gives you something you can run with!
Paul

### CODE REVIEW

**Comment by Eh2406** [comment]
This Is really exciting. @semcogli has left for the day, but we will get into this tomorrow morning first thing. :-)

**Comment by Eh2406** [comment]
Hi, we looked this over this morning. It looks good. We then got distracted with getting many other steps to run, in preparation for the merg. We will be running on our hardware this afternoon. We will let you know how it goes. 

Some other random thoughts from reading this over this morning:
(Please don't take this as to-do's nor as criticism. They are intended as just some quick reactions. :-))
- Sorry about the `mismatched_data_description.yaml` it is from a half baked data qaqc thing we never really used, I added finishing that project to my todo list. :-)
- I'd go ahead and remove the old feasibility and developer. It will simplify the diff, and we can always use git to get the original back.
-  `proforma_settings.py` could use a verb in the name. Like "make_" or something. Also a one line comment describing what it does. Like "Converts from default ProForma settings to a yaml file with our customizations. Useful any time the yaml configuration format changes."
- Why did `parcel_average_price` need to be copied?
- `proforma.md` is very helpful notes on the methodology. Perhaps that content could have gon in a multi line commit message in each commit. The commit message provides an easy to find place for notes on the purpose of historical commits.

Thank you so much for the help and the clear explanations! We will let you know how it goes on our hardware.

**Comment by pksohn** [comment]
Thanks Jacob - those are all helpful points and good feedback. I'm going to make a very quick update to the PR. FYI I removed the `df` parameter from `parcel_average_price` to be consistent with the expected format, hence the copy + minor edit.

**Comment by Eh2406** [comment]
Hi, Good news. It runs on our hardware! We also added the changes for nonres. Do they look right?
We are trying to figure out if all the things `utils.run_feasibility` and `run_developer` are accounted for in the `parcel_utils` versions. Any advice?

**Pull request merged**
