### PR TITLE
HLCM specs by large area and income quartile

### PR DESCRIPTION
**Pull request by janowicz**
- The new HLCM model configuration files are in /configs/hlcm/large_area_income_quartile.
- Some additional configs to support automatic registration of the models are in the /configs directory.

### CODE REVIEW

**Comment by Eh2406** [comment]
I am going to test a merge of #9 and #8 on our hardware, we will let you know how it goes. :-)

**Comment by janowicz** [comment]
Sounds good, keep me posted :)

I won't be able to get to the update of the hlcm config model expressions from a list of variables to `patsy` string today, but its on my todo list.

**Comment by Eh2406** [comment]
Ok, so it crashed in `Running iteration 19 with iteration value 2034` With:

```
	Running step 'hlcm/large_area_income_quartile/hlcm300161'
1057 agents are making a choice.
There are 172712.0 total available units     and 1057 total choosers     but there are 0 overfull alternatives
    for a total of 308.0 temporarily empty units     in 308 alternatives total in the region
There are 1057 total movers for this LCM
WARNING: Not enough locations for movers reducing locations to size of movers for performance gain
Choice mode is individual, so utilizing lottery choices.
Traceback (most recent call last):
  File "/home/da/semcog/semcog_urbansim/Simulation.py", line 54, in <module>
    compress=True)
  File "/home/da/anaconda2/lib/python2.7/site-packages/orca/orca.py", line 1987, in run
    step()
  File "/home/da/anaconda2/lib/python2.7/site-packages/orca/orca.py", line 792, in __call__
    return self._func(**kwargs)
  File "/home/da/semcog/semcog_urbansim/lcm_utils.py", line 157, in choice_model_simulate
    choices = model.simulate(choice_function=choice_function)
  File "/home/da/semcog/semcog_urbansim/lcm_utils.py", line 254, in simulate
    choices = choice_function(self, choosers, alternatives, **kwargs)
  File "/home/da/semcog/semcog_urbansim/lcm_utils.py", line 131, in unit_choices
    next_choices = model.predict(choosers, units_remaining)
  File "/home/da/udst/urbansim/urbansim/models/dcm.py", line 635, in predict
    choosers, alternatives, filter_tables=False)
  File "/home/da/udst/urbansim/urbansim/models/dcm.py", line 515, in probabilities
    choosers, alternatives, sample_size)
  File "/home/da/udst/urbansim/urbansim/urbanchoice/interaction.py", line 82, in mnl_interaction_dataset
    assert len(alts_sample.index) == SAMPLE_SIZE * len(choosers.index)
AssertionError
Closing remaining open files:./data/semcog_networks.h5...done./data/all_semcog_data_08-17-17.h5...done

Process finished with exit code 1
```

Looks like using this will have to wait for proforma to get fixed.

**Comment by janowicz** [comment]
Ah yes, you're right-  looks like there are too few residential units in that large area.  We could potentially put a try/except in the short term to get past this, but then households would be going unplaced (floating without a building_id).

**Pull request merged**
